"use client";
import {useEffect,useRef,useState} from "react";
import "./groove-course.css";

type Cond="A"|"B"|"C";
const MODULES=["PERCEIVE","INQUIRE","EXPLORE","COMPRESS","EXPAND"];
const HEADS=["Which loop gives you the clearest clock?","What makes a pulse easy to find?","Can the pulse survive missing sounds?","What is a pulse?","Build a clock the body can find."];
const PATTERNS:Record<Cond,number[]>={A:[0,4,8,12],B:[0,2,4,6,8,10,12,14],C:[0,3,7,10,14]};

export default function GrooveCoursePage(){
 const [module,setModule]=useState(1),[cond,setCond]=useState<Cond>("A"),[choice,setChoice]=useState<Cond|null>(null),[playing,setPlaying]=useState(false),[step,setStep]=useState(-1),[mask,setMask]=useState([0,4,8,12]),[custom,setCustom]=useState([0,4,8,12]),[verdict,setVerdict]=useState<string|null>(null);
 const ctx=useRef<AudioContext|null>(null),timer=useRef<number|null>(null),live=useRef({module,cond,mask,custom});
 useEffect(()=>{live.current={module,cond,mask,custom}},[module,cond,mask,custom]);
 function audio(){if(!ctx.current)ctx.current=new AudioContext();if(ctx.current.state==="suspended")void ctx.current.resume();return ctx.current}
 function click(i:number){const c=audio(),o=c.createOscillator(),g=c.createGain(),t=c.currentTime;o.type="sine";o.frequency.value=i%4===0?92:155;g.gain.setValueAtTime(i%4===0?.65:.35,t);g.gain.exponentialRampToValueAtTime(.001,t+.09);o.connect(g).connect(c.destination);o.start(t);o.stop(t+.1)}
 function active(i:number){const l=live.current,p=l.module===3?l.mask:l.module===5?l.custom:PATTERNS[l.cond];return p.includes(i)}
 function stop(){if(timer.current)clearInterval(timer.current);timer.current=null;setPlaying(false);setStep(-1)}
 function play(){if(playing){stop();return}audio();let i=0;if(active(i))click(i);setStep(i);setPlaying(true);timer.current=window.setInterval(()=>{i=(i+1)%16;if(active(i))click(i);setStep(i)},(60/112/4)*1000)}
 useEffect(()=>()=>{if(timer.current)clearInterval(timer.current)},[]);
 function toggleMask(i:number){setMask(p=>p.includes(i)?p.filter(x=>x!==i):[...p,i].sort((a,b)=>a-b))}
 function toggleCustom(i:number){setVerdict(null);setCustom(p=>p.includes(i)?p.filter(x=>x!==i):[...p,i].sort((a,b)=>a-b))}
 function submit(){if(custom.length<2){setVerdict("TOO LITTLE INFORMATION — with fewer than two events, there is not enough repetition to strongly establish a periodic clock.");return}const sorted=[...custom].sort((a,b)=>a-b),gaps=sorted.map((x,i)=>i===sorted.length-1?16-x+sorted[0]:sorted[i+1]-x),mean=gaps.reduce((a,b)=>a+b,0)/gaps.length,variance=gaps.reduce((s,x)=>s+(x-mean)**2,0)/gaps.length;if(variance<.35)setVerdict("STRONG PERIODIC PULSE — your events repeat at nearly equal intervals, giving the listener a clear temporal prediction.");else if(variance<2)setVerdict("RECOVERABLE BUT UNEVEN — there is some periodic support, but the intervals vary. Can your body still infer a steady clock underneath?");else setVerdict("WEAK PERIODIC SUPPORT — event spacing changes substantially, so the sounded pattern provides little direct evidence for one steady pulse.")}
 const pattern=module===3?mask:module===5?custom:PATTERNS[cond];
 return <main className="gc-shell"><aside className="gc-rail"><div className="gc-brand">MZCMG // GROOVE CORE</div><div className="gc-sub">COURSE // LESSON 01 // PULSE</div>{MODULES.map((m,i)=><button key={m} className={`gc-nav ${module===i+1?"active":""}`} onClick={()=>setModule(i+1)}><b>0{i+1}</b><span>{m}</span></button>)}</aside><section className="gc-main"><header className="gc-top"><div><div className="gc-eyebrow">PIECE // {MODULES[module-1]}</div><h1>{HEADS[module-1]}</h1></div><div className="gc-progress">{MODULES[module-1]} // {module}/5</div></header><section className="gc-stage">
 {module===1&&<><div className="gc-instruction"><b>PERCEIVE</b><span>Listen to A, B, and C. Don’t count. Which one gives your body the clearest repeating clock?</span></div><ABC cond={cond} set={setCond}/><div className="gc-choose"><span>Which feels clearest?</span>{(["A","B","C"] as Cond[]).map(c=><button key={c} onClick={()=>{setChoice(c);setCond(c)}}>CHOOSE {c}</button>)}</div>{choice&&<div className={`gc-zone ${choice==="A"?"supported":"partial"}`}><b>{choice==="A"?"RESEARCH-ALIGNED EXAMPLE":"INTERESTING RESPONSE"}</b><span>{choice==="A"?"A gives a simple, equally spaced event every beat. That regularity supplies especially clear evidence for a periodic pulse.":`${choice} felt clearest to you. A is the deliberately simplest periodic condition, but pulse perception is an inference: listeners can find a clock in richer or uneven patterns too.`}</span></div>}</>}
 {module===2&&<><div className="gc-instruction"><b>INQUIRE</b><span>Now look. A repeats every four steps. B repeats twice as often. C uses uneven spacing. What property makes A and B easier to predict?</span></div><ABC cond={cond} set={setCond}/><Grid pattern={PATTERNS[cond]} step={step}/><div className="gc-concept"><b>QUESTION</b><span>Is the pulse the sound itself — or the regular timing your perceptual system infers from repeated sound?</span></div></>}
 {module===3&&<><div className="gc-instruction"><b>EXPLORE</b><span>The underlying clock is still four beats per bar. Click pulse events off and on while the loop plays. How many can disappear before you stop feeling four steady beats?</span></div><Editable pattern={mask} step={step} toggle={toggleMask}/><div className="gc-sandbox-actions"><button onClick={()=>setMask([0,4,8,12])}>ALL 4 SOUNDED</button><button onClick={()=>setMask([0,8])}>ONLY 1 + 3</button><button onClick={()=>setMask([0])}>ONLY 1</button><button onClick={()=>setMask([])}>SILENCE</button></div><div className="gc-concept"><b>NOTICE</b><span>A pulse can remain perceptually present even when some pulse positions are not sounded. Your system predicts through the gaps.</span></div></>}
 {module===4&&<><div className="gc-instruction"><b>COMPRESS</b><span>You’ve heard the distinction. Now name it.</span></div><div className="gc-concept"><b>PULSE</b><span>A perceived regular temporal structure — the repeating clock against which rhythmic events can be organized.</span></div><div className="gc-research"><b>SOUND ≠ PULSE</b><span>A sounded event can reinforce a pulse position, but the pulse itself is perceptual. It can continue through silence or through rhythms that do not explicitly sound every beat.</span></div><div className="gc-research"><b>WORKING MODEL</b><span>Regular events → temporal prediction → inferred periodic pulse. The stronger the periodic evidence, the easier the clock is to find and maintain.</span><small>We’ll complicate this immediately in Lesson 02: some events reinforce that inferred clock more strongly than others.</small></div></>}
 {module===5&&<><div className="gc-instruction"><b>EXPAND</b><span>Start empty. Place sounds anywhere on the 16-step bar. Your goal: make a repeating clock easy to infer.</span></div><div className="gc-sandbox-actions"><button onClick={()=>{setCustom([]);setVerdict(null)}}>CLEAR</button><button onClick={()=>{setCustom([0,4,8,12]);setVerdict(null)}}>LOAD 4-BEAT PULSE</button></div><Editable pattern={custom} step={step} toggle={toggleCustom}/><button className="gc-submit" onClick={submit}>ANALYZE MY PULSE →</button>{verdict&&<div className="gc-verdict groovy"><div className="gc-verdict-title"><small>PERIODICITY CHECK</small><b>{verdict.split(" — ")[0]}</b></div><p>{verdict.split(" — ")[1]}</p><small>This checks spacing regularity, not whether your rhythm is musically “good.”</small></div>}<div className="gc-concept"><b>NEXT QUESTION</b><span>If pulse is inferred rather than simply sounded, what kinds of sonic events make that clock easiest for the body to hold onto?</span></div><div className="gc-research"><b>LESSON 02 // PULSE ANCHORS</b><span>What keeps the clock perceptible?</span></div></>}
 </section><div className="gc-playbar"><button className={playing?"on":""} onClick={play}>{playing?"■ STOP LOOP":"▶ PLAY LOOP"}</button><span>112 BPM // 16 STEPS</span>{module<5?<button className="gc-next" onClick={()=>setModule(m=>Math.min(5,m+1))}>NEXT // {MODULES[module]} →</button>:<span className="gc-done">PIECE LOOP COMPLETE</span>}</div></section></main>
}
function ABC({cond,set}:{cond:Cond;set:(c:Cond)=>void}){return <div className="gc-compare">{(["A","B","C"] as Cond[]).map(c=><button key={c} className={cond===c?"active":""} onClick={()=>set(c)}><small>LOOP</small><b>{c}</b><span>▶ select + listen</span></button>)}</div>}
function Grid({pattern,step}:{pattern:number[];step:number}){return <div className="gc-seq"><div className="gc-beatnums"><label>STEP</label>{Array.from({length:16},(_,i)=><b key={i} className={i%4===0?"strong":""}>{i%4===0?i/4+1:"·"}</b>)}</div><div className="gc-lane"><label>EVENT</label>{Array.from({length:16},(_,i)=><i key={i} className={`${i%4===0?"beat ":""}${pattern.includes(i)?"hit ":""}${step===i?"head":""}`}/>)}</div></div>}
function Editable({pattern,step,toggle}:{pattern:number[];step:number;toggle:(i:number)=>void}){return <div className="gc-seq gc-editable"><div className="gc-beatnums"><label>STEP</label>{Array.from({length:16},(_,i)=><b key={i} className={i%4===0?"strong":""}>{i%4===0?i/4+1:"·"}</b>)}</div><div className="gc-lane"><label>EVENT</label>{Array.from({length:16},(_,i)=><button aria-label={`step ${i+1}`} key={i} onClick={()=>toggle(i)} className={`${i%4===0?"beat ":""}${pattern.includes(i)?"hit ":""}${step===i?"head":""}`}/>)}</div></div>}
