"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import "./groove-course.css";

type Mode = "STRICT" | "SYNC" | "DESTABILIZED";
type Pattern = { kick:number[]; snare:number[]; hat:number[]; moved:number[] };
type Verdict = { label:"STRICT"|"MODERATELY SYNCOPATED"|"DESTABILIZED"; detail:string; displaced:number; support:number; density:number };

const MODE: Record<Mode,{label:string;sync:number}>={
  STRICT:{label:"A",sync:8}, SYNC:{label:"B",sync:48}, DESTABILIZED:{label:"C",sync:92}
};
const straightHat=[0,2,4,6,8,10,12,14], offbeats=[1,3,5,7,9,11,13,15];
const moduleNames=["FEEL FIRST","REVEAL THE DIFFERENCE","NAME IT","FIND THE RANGE","BUILD YOUR OWN"];
const moduleHeads=["Which loop makes you want to move?","What actually changed?","This is syncopation.","How much is enough?","Can you build it yourself?"];

function patternFor(sync:number):Pattern{
  const hats=new Set(straightHat), moved:number[]=[];
  const moveCount=sync<20?0:sync<70?3:7;
  for(let i=0;i<moveCount;i++){ const from=straightHat[(i*3)%8],to=offbeats[(i*2+1)%8]; hats.delete(from); hats.add(to); moved.push(to); }
  return {kick:[0,4,8,12],snare:[4,12],hat:[...hats].sort((a,b)=>a-b),moved};
}
function toggleStep(list:number[],i:number){return list.includes(i)?list.filter(x=>x!==i):[...list,i].sort((a,b)=>a-b)}

export default function GrooveCoursePage(){
 const [module,setModule]=useState(1),[mode,setMode]=useState<Mode>("STRICT"),[playing,setPlaying]=useState(false),[step,setStep]=useState(-1);
 const [choice,setChoice]=useState<Mode|null>(null),[revealed,setRevealed]=useState(false);
 const [custom,setCustom]=useState<Pattern>({kick:[0,4,8,12],snare:[4,12],hat:[0,2,5,8,10,13],moved:[5,13]});
 const [verdict,setVerdict]=useState<Verdict|null>(null),ctxRef=useRef<AudioContext|null>(null),timerRef=useRef<number|null>(null),liveRef=useRef({mode,module,custom});
 useEffect(()=>{liveRef.current={mode,module,custom}},[mode,module,custom]);
 const pattern=useMemo(()=>module===5?custom:patternFor(MODE[mode].sync),[mode,module,custom]);
 function ensure(){if(!ctxRef.current)ctxRef.current=new AudioContext();if(ctxRef.current.state==="suspended")void ctxRef.current.resume();return ctxRef.current}
 function hit(ctx:AudioContext,time:number,type:"kick"|"snare"|"hat"){
  if(type==="kick"){const o=ctx.createOscillator(),g=ctx.createGain();o.type="sine";o.frequency.setValueAtTime(125,time);o.frequency.exponentialRampToValueAtTime(48,time+.11);g.gain.setValueAtTime(.78,time);g.gain.exponentialRampToValueAtTime(.001,time+.18);o.connect(g).connect(ctx.destination);o.start(time);o.stop(time+.2);return}
  const len=type==="snare"?.1:.032,b=ctx.createBuffer(1,Math.floor(ctx.sampleRate*len),ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*(1-i/d.length);
  const s=ctx.createBufferSource(),f=ctx.createBiquadFilter(),g=ctx.createGain();s.buffer=b;f.type="highpass";f.frequency.value=type==="snare"?900:5200;g.gain.value=type==="snare"?.27:.12;s.connect(f).connect(g).connect(ctx.destination);s.start(time)
 }
 function fireStep(i:number){const ctx=ensure(),live=liveRef.current,p=live.module===5?live.custom:patternFor(MODE[live.mode].sync),now=ctx.currentTime;if(p.kick.includes(i))hit(ctx,now,"kick");if(p.snare.includes(i))hit(ctx,now,"snare");if(p.hat.includes(i))hit(ctx,now,"hat")}
 function stop(){if(timerRef.current)window.clearInterval(timerRef.current);timerRef.current=null;setPlaying(false);setStep(-1)}
 function play(){if(playing){stop();return}ensure();let i=0;fireStep(i);setStep(i);setPlaying(true);timerRef.current=window.setInterval(()=>{i=(i+1)%16;fireStep(i);setStep(i)},(60/116/4)*1000)}
 useEffect(()=>()=>{if(timerRef.current)window.clearInterval(timerRef.current)},[]);
 function choose(m:Mode){setMode(m);setChoice(m);setRevealed(true)}
 function editCustom(lane:"kick"|"snare"|"hat",i:number){setVerdict(null);setCustom(p=>{const next={...p,[lane]:toggleStep(p[lane],i)} as Pattern;return{...next,moved:next.hat.filter(x=>offbeats.includes(x))}})}
 function resetCustom(){setVerdict(null);setCustom({kick:[0,4,8,12],snare:[4,12],hat:[0,2,4,6,8,10,12,14],moved:[]})}
 function submitCustom(){const displaced=custom.hat.filter(i=>offbeats.includes(i)).length,missing=straightHat.filter(i=>!custom.hat.includes(i)).length,complexity=displaced+missing,support=[0,4,8,12].filter(i=>custom.kick.includes(i)).length+[4,12].filter(i=>custom.snare.includes(i)).length,density=custom.kick.length+custom.snare.length+custom.hat.length;let label:Verdict["label"],detail:string;if(complexity<=2){label="STRICT";detail="Most events stay close to the expected metric grid. The pulse is easy to recover, with little expectation violation."}else if(complexity<=7&&support>=4&&density<=20){label="MODERATELY SYNCOPATED";detail="The meter remains recoverable while several events challenge expected positions. This is the region that commonly produces stronger movement responses in the research."}else{label="DESTABILIZED";detail=support<4?"Too much of the pulse scaffold has disappeared. Rebuild a few anchors and listen again.":"Many events challenge the grid at once. Reduce a few displacements and see whether the pulse becomes easier to inhabit."}setVerdict({label,detail,displaced,support,density})}
 const feedback=choice==="SYNC"?"Research tends to agree with your choice. Across groups of listeners, intermediate syncopation often produces the strongest pleasurable urge to move.":choice?`Interesting. You chose ${MODE[choice].label}. Population-level studies often favor B, the moderately syncopated condition. Your response is still useful data about your own movement preference.`:"";
 return <main className="gc-shell"><aside className="gc-rail"><div className="gc-brand">MZCMG // GROOVE CORE</div><div className="gc-sub">COURSE // LESSON 01</div>{[1,2,3,4,5].map(n=><button key={n} className={`gc-nav ${module===n?"active":""}`} onClick={()=>setModule(n)}><b>0{n}</b><span>{moduleNames[n-1]}</span></button>)}</aside>
 <section className="gc-main"><header className="gc-top"><div><div className="gc-eyebrow">SYNCOPATION LAB</div><h1>{moduleHeads[module-1]}</h1></div><div className="gc-progress">MODULE {module} / 5</div></header><section className="gc-stage">
 {module===1&&<><div className="gc-instruction"><b>LISTEN</b><span>Play A, B, and C. Don’t analyze them yet. Which one gives you the strongest urge to move?</span></div><div className="gc-compare">{(["STRICT","SYNC","DESTABILIZED"] as Mode[]).map(m=><button key={m} className={mode===m?"active":""} onClick={()=>setMode(m)}><small>LOOP</small><b>{MODE[m].label}</b><span>▶ hear this loop</span></button>)}</div><div className="gc-choose"><span>Commit to your answer:</span>{(["STRICT","SYNC","DESTABILIZED"] as Mode[]).map(m=><button key={m} onClick={()=>choose(m)}>CHOOSE {MODE[m].label}</button>)}</div>{revealed&&<div className={`gc-zone ${choice==="SYNC"?"supported":"partial"}`}><b>{choice==="SYNC"?"RESEARCH TENDS TO AGREE":"YOUR RESPONSE ≠ POPULATION TENDENCY"}</b><span>{feedback}</span></div>}</>}
 {module===2&&<><div className="gc-instruction"><b>LOOK</b><span>Now compare the loops again. The yellow squares show events moved away from expected positions.</span></div><Compare mode={mode} setMode={setMode}/><BeatView pattern={pattern} step={step}/><div className="gc-concept"><b>ONE CHANGE</b><span>The underlying pulse stays the same. What changes is how often events land away from the positions the meter makes you expect.</span></div></>}
 {module===3&&<><div className="gc-instruction"><b>NAME IT</b><span>Those expectation-breaking placements have a name: syncopation.</span></div><Compare mode={mode} setMode={setMode}/><BeatView pattern={pattern} step={step}/><div className="gc-concept"><b>SYNCOPATION</b><span>Rhythmic events challenge expected metric positions while an underlying pulse remains perceptible.</span></div><div className="gc-research"><b>THE IMPORTANT PART</b><span>Syncopation is not the same thing as groove. It is one musical variable that can influence the urge to move.</span></div></>}
 {module===4&&<><div className="gc-instruction"><b>TEST</b><span>Move A → B → C again. Listen for the point where expectation violation creates tension without making the pulse hard to recover.</span></div><Compare mode={mode} setMode={setMode}/><ResearchMeter mode={mode}/><BeatView pattern={pattern} step={step}/><div className={`gc-zone ${mode==="SYNC"?"supported":mode==="STRICT"?"partial":"outside"}`}><b>{mode==="STRICT"?"STRICT":mode==="SYNC"?"MODERATELY SYNCOPATED":"DESTABILIZED"}</b><span>{mode==="STRICT"?"Events mostly obey the metric grid. Clear pulse, little expectation violation.":mode==="SYNC"?"The pulse remains recoverable while several events challenge it. This intermediate region commonly produces stronger PLUMM ratings.":"Many expectations are violated at once, making the underlying meter harder to recover."}</span></div><div className="gc-research"><b>WITEK ET AL. 2014</b><span>Across their stimuli, pleasure and wanting-to-move tended to peak at intermediate syncopation — an inverted-U rather than a “more is better” rule.</span><small>Population tendency, not a universal law.</small></div></>}
 {module===5&&<><div className="gc-instruction"><b>BUILD</b><span>Start strict. Move or add events until you can feel tension around the pulse without losing it.</span></div><div className="gc-sandbox-actions"><button onClick={resetCustom}>START STRICT</button></div><EditableBeatView pattern={custom} step={step} edit={editCustom}/><button className="gc-submit" onClick={submitCustom}>SUBMIT RHYTHM →</button>{verdict&&<div className={`gc-verdict ${verdict.label==="MODERATELY SYNCOPATED"?"groovy":verdict.label==="STRICT"?"straight":"much"}`}><div className="gc-verdict-title"><small>LESSON HEURISTIC</small><b>{verdict.label}</b></div><p>{verdict.detail}</p><div className="gc-verdict-metrics"><span><b>{verdict.displaced}</b> offbeat hats</span><span><b>{verdict.support}/6</b> pulse anchors</span><span><b>{verdict.density}</b> total events</span></div><small>This applies the simplified lesson model. It is not a scientific groove detector.</small></div>}</>}
 </section><div className="gc-playbar"><button className={playing?"on":""} onClick={play}>{playing?"■ STOP LOOP":"▶ PLAY LOOP"}</button><span>116 BPM // 16 STEPS</span>{module<5?<button className="gc-next" onClick={()=>setModule(m=>Math.min(5,m+1))}>NEXT MODULE →</button>:<span className="gc-done">LESSON COMPLETE</span>}</div></section></main>
}

function Compare({mode,setMode}:{mode:Mode;setMode:(m:Mode)=>void}){return <div className="gc-compare">{(["STRICT","SYNC","DESTABILIZED"] as Mode[]).map(m=><button key={m} className={mode===m?"active":""} onClick={()=>setMode(m)}><small>LOOP</small><b>{MODE[m].label}</b><span>{m==="STRICT"?"strict":m==="SYNC"?"moderate":"high displacement"}</span></button>)}</div>}
function BeatView({pattern,step}:{pattern:Pattern;step:number}){return <div className="gc-seq"><div className="gc-beatnums"><label>STEP</label>{Array.from({length:16},(_,i)=><b key={i} className={i%4===0?"strong":""}>{i%4===0?i/4+1:"·"}</b>)}</div>{(["kick","snare","hat"] as const).map(l=><div className="gc-lane" key={l}><label>{l.toUpperCase()}</label>{Array.from({length:16},(_,i)=><i key={i} className={`${i%4===0?"beat ":""}${pattern[l].includes(i)?"hit ":""}${pattern.moved.includes(i)&&l==="hat"?"moved ":""}${step===i?"head":""}`}/>)}</div>)}</div>}
function EditableBeatView({pattern,step,edit}:{pattern:Pattern;step:number;edit:(l:"kick"|"snare"|"hat",i:number)=>void}){return <div className="gc-seq gc-editable">{(["kick","snare","hat"] as const).map(l=><div className="gc-lane" key={l}><label>{l.toUpperCase()}</label>{Array.from({length:16},(_,i)=><button aria-label={`${l} step ${i+1}`} key={i} onClick={()=>edit(l,i)} className={`${i%4===0?"beat ":""}${pattern[l].includes(i)?"hit ":""}${pattern.moved.includes(i)&&l==="hat"?"moved ":""}${step===i?"head":""}`}/>)}</div>)}</div>}
function ResearchMeter({mode}:{mode:Mode}){const x=mode==="STRICT"?12:mode==="SYNC"?50:88;return <div className="gc-meter"><div className="gc-meterlabels"><span>STRICT</span><b>COMMON HIGHER-MOVEMENT REGION</b><span>DESTABILIZED</span></div><div className="gc-meterbar"><div className="gc-sweet"/><i style={{left:`${x}%`}}/></div><small>Research describes a tendency across listeners. Your own response may differ.</small></div>}
